CREATE TABLE Candidato
  (
    IDCandidato    INTEGER NOT NULL ,
    NomeCompleto   VARCHAR2 (80) NOT NULL ,
    NomePopular    VARCHAR2 (80) NOT NULL ,
    DataNascimento DATE NOT NULL ,
    IDCidade       INTEGER NOT NULL ,
    RegistroTRE    VARCHAR2 (30) NOT NULL ,
    Foto           VARCHAR2 (200) NOT NULL ,
    IDPartido      INTEGER NOT NULL ,
    NumeroEscolha  VARCHAR2 (5) NOT NULL ,
    IDTipoCargo    INTEGER NOT NULL
  ) ;
ALTER TABLE Candidato ADD CONSTRAINT Candidato_PK PRIMARY KEY ( IDCandidato ) ;
ALTER TABLE Candidato ADD CONSTRAINT UK_Candidato_NumeroEscolha UNIQUE ( NumeroEscolha ) ;
ALTER TABLE Candidato ADD CONSTRAINT UK_Candidato_RegistroTRE UNIQUE ( RegistroTRE ) ;


CREATE TABLE Cidade
  (
    IDCidade INTEGER NOT NULL ,
    Nome     VARCHAR2 (80) NOT NULL ,
    IDEstado INTEGER NOT NULL
  ) ;
ALTER TABLE Cidade ADD CONSTRAINT Cidade_PK PRIMARY KEY ( IDCidade ) ;


CREATE TABLE Eleitor
  (
    IDEleitor      INTEGER NOT NULL ,
    NomeCompleto   VARCHAR2 (80) NOT NULL ,
    TituloEleitor  VARCHAR2 (15) NOT NULL ,
    RG             VARCHAR2 (15) NOT NULL ,
    DataNascimento DATE NOT NULL ,
    IDSecaoZona    INTEGER NOT NULL ,
    Voto           CHAR (1) NOT NULL
  ) ;
ALTER TABLE Eleitor ADD CONSTRAINT Eleitor_PK PRIMARY KEY ( IDEleitor ) ;
ALTER TABLE Eleitor ADD CONSTRAINT UK_Eleitor_RG UNIQUE ( RG ) ;
ALTER TABLE Eleitor ADD CONSTRAINT UK_Eleitor_TituloEleitor UNIQUE ( TituloEleitor ) ;


CREATE TABLE Estado
  (
    IDEstado INTEGER NOT NULL ,
    Nome     VARCHAR2 (40) NOT NULL
  ) ;
ALTER TABLE Estado ADD CONSTRAINT Estado_PK PRIMARY KEY ( IDEstado ) ;


CREATE TABLE Partido
  (
    IDPartido INTEGER NOT NULL ,
    Nome      VARCHAR2 (80) NOT NULL
  ) ;
ALTER TABLE Partido ADD CONSTRAINT Partido_PK PRIMARY KEY ( IDPartido ) ;


CREATE TABLE Secao
  (
    IDSecao INTEGER NOT NULL ,
    Codigo  VARCHAR2 (4) NOT NULL
  ) ;
ALTER TABLE Secao ADD CONSTRAINT Secao_PK PRIMARY KEY ( IDSecao ) ;
ALTER TABLE Secao ADD CONSTRAINT UK_Secao UNIQUE ( Codigo ) ;


CREATE TABLE SecaoZona
  (
    IDSecaoZona INTEGER NOT NULL ,
    IDSecao     INTEGER NOT NULL ,
    IDZona      INTEGER NOT NULL
  ) ;
ALTER TABLE SecaoZona ADD CONSTRAINT SecaoZona_PK PRIMARY KEY ( IDSecaoZona ) ;
ALTER TABLE SecaoZona ADD CONSTRAINT UK_SecaoZona UNIQUE ( IDSecao , IDZona ) ;


CREATE TABLE TipoCargo
  (
    IDTipoCargo INTEGER NOT NULL ,
    Nome        VARCHAR2 (60) NOT NULL
  ) ;
ALTER TABLE TipoCargo ADD CONSTRAINT TipoCargo_PK PRIMARY KEY ( IDTipoCargo ) ;


CREATE TABLE Voto
  (
    IDVoto        INTEGER NOT NULL ,
    NumeroEscolha VARCHAR2 (5) NOT NULL
  ) ;
ALTER TABLE Voto ADD CONSTRAINT Voto_PK PRIMARY KEY ( IDVoto ) ;


CREATE TABLE Zona
  ( IDZona INTEGER NOT NULL , Codigo VARCHAR2 (4) NOT NULL
  ) ;
ALTER TABLE Zona ADD CONSTRAINT Zona_PK PRIMARY KEY ( IDZona ) ;
ALTER TABLE Zona ADD CONSTRAINT UK_Zona UNIQUE ( Codigo ) ;


ALTER TABLE Eleitor ADD CONSTRAINT Eleitor_SecaoZona_FK FOREIGN KEY ( IDSecaoZona ) REFERENCES SecaoZona ( IDSecaoZona ) ;

ALTER TABLE Candidato ADD CONSTRAINT FK_Candidato_Cidade FOREIGN KEY ( IDCidade ) REFERENCES Cidade ( IDCidade ) ;

ALTER TABLE Candidato ADD CONSTRAINT FK_Candidato_Partido FOREIGN KEY ( IDPartido ) REFERENCES Partido ( IDPartido ) ;

ALTER TABLE Candidato ADD CONSTRAINT FK_Candidato_TipoCargo FOREIGN KEY ( IDTipoCargo ) REFERENCES TipoCargo ( IDTipoCargo ) ;

ALTER TABLE Cidade ADD CONSTRAINT FK_Cidade_Estado FOREIGN KEY ( IDEstado ) REFERENCES Estado ( IDEstado ) ;

ALTER TABLE SecaoZona ADD CONSTRAINT FK_SecaoZona_Secao FOREIGN KEY ( IDSecao ) REFERENCES Secao ( IDSecao ) ;

ALTER TABLE SecaoZona ADD CONSTRAINT FK_SecaoZona_Zona FOREIGN KEY ( IDZona ) REFERENCES Zona ( IDZona ) ;

CREATE SEQUENCE Candidato_IDCandidato_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER Candidato_IDCandidato_TRG BEFORE
  INSERT ON Candidato FOR EACH ROW WHEN (NEW.IDCandidato IS NULL) BEGIN :NEW.IDCandidato := Candidato_IDCandidato_SEQ.NEXTVAL;
END;
/

CREATE SEQUENCE Cidade_IDCidade_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER Cidade_IDCidade_TRG BEFORE
  INSERT ON Cidade FOR EACH ROW WHEN (NEW.IDCidade IS NULL) BEGIN :NEW.IDCidade := Cidade_IDCidade_SEQ.NEXTVAL;
END;
/

CREATE SEQUENCE Eleitor_IDEleitor_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER Eleitor_IDEleitor_TRG BEFORE
  INSERT ON Eleitor FOR EACH ROW WHEN (NEW.IDEleitor IS NULL) BEGIN :NEW.IDEleitor := Eleitor_IDEleitor_SEQ.NEXTVAL;
END;
/

CREATE SEQUENCE Estado_IDEstado_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER Estado_IDEstado_TRG BEFORE
  INSERT ON Estado FOR EACH ROW WHEN (NEW.IDEstado IS NULL) BEGIN :NEW.IDEstado := Estado_IDEstado_SEQ.NEXTVAL;
END;
/

CREATE SEQUENCE Partido_IDPartido_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER Partido_IDPartido_TRG BEFORE
  INSERT ON Partido FOR EACH ROW WHEN (NEW.IDPartido IS NULL) BEGIN :NEW.IDPartido := Partido_IDPartido_SEQ.NEXTVAL;
END;
/

CREATE SEQUENCE Secao_IDSecao_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER Secao_IDSecao_TRG BEFORE
  INSERT ON Secao FOR EACH ROW WHEN (NEW.IDSecao IS NULL) BEGIN :NEW.IDSecao := Secao_IDSecao_SEQ.NEXTVAL;
END;
/

CREATE SEQUENCE SecaoZona_IDSecaoZona_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER SecaoZona_IDSecaoZona_TRG BEFORE
  INSERT ON SecaoZona FOR EACH ROW WHEN (NEW.IDSecaoZona IS NULL) BEGIN :NEW.IDSecaoZona := SecaoZona_IDSecaoZona_SEQ.NEXTVAL;
END;
/

CREATE SEQUENCE TipoCargo_IDTipoCargo_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER TipoCargo_IDTipoCargo_TRG BEFORE
  INSERT ON TipoCargo FOR EACH ROW WHEN (NEW.IDTipoCargo IS NULL) BEGIN :NEW.IDTipoCargo := TipoCargo_IDTipoCargo_SEQ.NEXTVAL;
END;
/

CREATE SEQUENCE Voto_IDVoto_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER Voto_IDVoto_TRG BEFORE
  INSERT ON Voto FOR EACH ROW WHEN (NEW.IDVoto IS NULL) BEGIN :NEW.IDVoto := Voto_IDVoto_SEQ.NEXTVAL;
END;
/

CREATE SEQUENCE Zona_IDZona_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER Zona_IDZona_TRG BEFORE
  INSERT ON Zona FOR EACH ROW WHEN (NEW.IDZona IS NULL) BEGIN :NEW.IDZona := Zona_IDZona_SEQ.NEXTVAL;
END;
/